name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies for backend
      working-directory: ./server
      run: npm install


    - name: Install dependencies for frontend
      working-directory: ./client
      run: npm install

    - name: Build and test frontend
      working-directory: ./client
      run: |
        npm run build

    - name: Deploy backend
      working-directory: ./server
      env:
        MYSQL_HOST: localhost
        MYSQL_PORT: 3306
        MYSQL_DATABASE: node_app
        MYSQL_USER: justme
        MYSQL_PASSWORD: justme@123
        NODE_ENV: production
      run: |
        sudo npm install -g pm2
        pm2 start index.js --name backend

    - name: Deploy frontend
      working-directory: ./client
      run: |
        sudo npm install -g pm2
        pm2 start npm --name frontend -- run dev
